#!/usr/bin/bash
#PL:gencode_version:22-49
#TARGET:grch38/gtf-gencode/{gencode_version}
#WHATIS:GRCh38 reference genome GTF for GENCODE {gencode_version}
#URL:https://www.gencodegenes.org/human/
#ENV:ANNOTATION_GTF=$app_root/gencode.v{gencode_version}.primary_assembly.annotation.gtf
#ENVNOTE:GRCh38 genome annotation GENCODE v{gencode_version}

install_app() {
    cd "$target_dir"
    url="https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_{gencode_version}/gencode.v{gencode_version}.primary_assembly.annotation.gtf.gz"
    print_stderr "Downloading ${YELLOW}${app_name_version}${NC}"
    wget -nv -O "gencode.v{gencode_version}.primary_assembly.annotation.gtf.gz" "$url"

    print_stderr "Extracting ${YELLOW}${app_name_version}${NC}"
    pigz_or_gunzip "gencode.v{gencode_version}.primary_assembly.annotation.gtf.gz"
}

# region common_functions
set -e
RED='\033[0;91m'
BLUE='\033[0;94m'
YELLOW='\033[0;93m'
NC='\033[0m'
NCPUS=${NCPUS:-4}

install() {
    print_stderr "Installing the target module: ${YELLOW}${app_name_version}${NC}"
    print_stderr "🎯 Target directory: $target_dir"
    if [ -d "$target_dir" ]; then
        print_stderr "${RED}ERROR${NC}: Target app dir exists!"
        exit 1
    fi
    if [[ -z "$tmp_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: tmp_dir is not set!"
        exit 1
    fi
    if [[ -z "$target_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: target_dir is not set!"
        exit 1
    fi
    mkdir -p "$target_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    install_app
    print_stderr "✅ Installation completed. ${YELLOW}${app_name_version}${NC} is ready to use."
}

print_stderr() {
    printf "[$(date +"%Y-%m-%d %T")] $1\n" 1>&2
}

pigz_or_gunzip() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $NCPUS "$1"
    else
        gunzip "$1"
    fi
}

pigz_or_gunzip_pipe() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $NCPUS -c "$1"
    else
        gunzip -c "$1"
    fi
}

tar_xf_pigz() {
    if command -v pigz &> /dev/null; then
        tar --no-same-owner --use-compress-program="pigz -d -p $NCPUS" -xf "$@"
    else
        tar --no-same-owner -xzf "$@"
    fi
}
#endregion

install
