#!/usr/bin/bash
#DEP:bwa-mem2/2.3>=2.0
#DEP:grch38/genome/ucsc_no_alt
#WHATIS:bwa-mem2 index for GRCh38 UCSC no alt reference genome
#URL:https://github.com/bwa-mem2/bwa-mem2
#ENV:BWA_MEM2_FASTA=$app_root/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
#ENVNOTE:GRCh38 reference genome

#SBATCH --cpus-per-task=1
#SBATCH --mem=80G
#SBATCH --time=4:00:00
#SBATCH --job-name=bwa-mem2-index
#SBATCH --output=%x-%j.log

install_app() {
    cd "$target_dir"

    BWA_MEM2_FASTA="GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"

    print_stderr "Copying reference genome FASTA to ${YELLOW}${app_name_version}${NC}"
    smart_copy_or_link "$GENOME_FASTA" "$BWA_MEM2_FASTA"
    smart_copy_or_link "$GENOME_FASTA.fai" "$BWA_MEM2_FASTA.fai"

    print_stderr "Indexing ${YELLOW}${app_name_version}${NC} with bwa-mem2 index"
    bwa-mem2 index -p "$BWA_MEM2_FASTA" "$BWA_MEM2_FASTA"
}

# region common_functions
set -e # exit on error
RED='\033[0;91m'
BLUE='\033[0;94m'
YELLOW='\033[0;93m'
NC='\033[0m'
NCPUS=${NCPUS:-4}

install() {
    print_stderr "Installing the target module: ${YELLOW}${app_name_version}${NC}"
    print_stderr "🎯 Target directory: $target_dir"
    if [ -d "$target_dir" ]; then
        print_stderr "${RED}ERROR${NC}: Target app dir exists!"
        exit 1
    fi
    if [[ -z "$tmp_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: tmp_dir is not set!"
        exit 1
    fi
    if [[ -z "$target_dir" ]]; then
        print_stderr "${RED}ERROR${NC}: target_dir is not set!"
        exit 1
    fi
    mkdir -p "$target_dir"
    mkdir -p "$tmp_dir"
    cd "$tmp_dir"
    install_app
    print_stderr "✅ Installation completed. ${YELLOW}${app_name_version}${NC} is ready to use."
}

print_stderr() {
    printf "[$(date +"%Y-%m-%d %T")] $1\n" 1>&2
}

pigz_or_gunzip() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $NCPUS "$1"
    else
        gunzip "$1"
    fi
}

pigz_or_gunzip_pipe() {
    if command -v pigz &> /dev/null; then
        pigz -d -p $NCPUS -c "$1"
    else
        gunzip -c "$1"
    fi
}

tar_xf_pigz() {
    if command -v pigz &> /dev/null; then
        tar --no-same-owner --use-compress-program="pigz -d -p $NCPUS" -xf "$@"
    else
        tar --no-same-owner -xzf "$@"
    fi
}

smart_copy_or_link() {
    local src="$1"
    local dst="$2"

    if [ -n "$IN_CONDATAINER" ]; then
        cp "$src" "$dst"
    else
        ln "$src" "$dst" || cp "$src" "$dst"
    fi
}
#endregion

install
